# Generated by Django 5.0.6 on 2024-06-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorando',
            fields=[
                ('iddoctorando', models.IntegerField(primary_key=True, serialize=False)),
                ('fdefensa', models.IntegerField(blank=True, null=True)),
                ('fingreso', models.IntegerField(blank=True, null=True)),
                ('temadetesis', models.CharField(max_length=100)),
                ('fingles', models.IntegerField(blank=True, null=True)),
                ('fespecialidad', models.IntegerField(blank=True, null=True)),
                ('desarrollolocal', models.BooleanField(blank=True, null=True)),
                ('facultadarea_idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('persona_idpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
