# Generated by Django 5.0.6 on 2024-06-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('areadeconocimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idprograma', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('sectorest', models.BooleanField()),
                ('desarrollolocal', models.BooleanField()),
                ('adistancia', models.BooleanField()),
                ('estdesarrollomun', models.BooleanField()),
                ('area_idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('areadeconocimiento_idareadeconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeconocimiento.areadeconocimiento')),
            ],
        ),
    ]
