# Generated by Django 5.0.6 on 2024-11-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0002_alter_centro_idcentro'),
        ('programa', '0002_alter_programa_idprograma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='area_idarea',
        ),
        migrations.AddField(
            model_name='programa',
            name='centro_idcentro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centro.centro'),
            preserve_default=False,
        ),
    ]
