# Generated by Django 5.0.6 on 2024-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='idpersona',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
