# Generated by Django 5.0.6 on 2024-09-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idpersona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
