# Generated by Django 5.0.6 on 2024-06-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('iddoctor', models.IntegerField(primary_key=True, serialize=False)),
                ('facultadarea_idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('persona_idpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
