# Generated by Django 5.0.6 on 2024-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='iddoctor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
