# Generated by Django 5.0.6 on 2024-10-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0002_alter_area_idarea'),
        ('areadeconocimiento', '0002_alter_areadeconocimiento_idareadeconocimiento'),
        ('persona', '0002_alter_persona_idpersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('idgraduado', models.AutoField(primary_key=True, serialize=False)),
                ('fechadefensa', models.DateField()),
                ('areadeconocimiento_idareadeconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeconocimiento.areadeconocimiento')),
                ('facultadarea_idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('persona_idpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
