# Generated by Django 5.0.6 on 2024-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areadeconocimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadeconocimiento',
            name='idareadeconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
